# Generated by Django 5.2.10 on 2026-02-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='category',
            field=models.CharField(choices=[('others', 'OTHERS')], default='others', max_length=16),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='target_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='type',
            field=models.CharField(choices=[('daily', 'DAILY'), ('weekly', 'WEEKLY'), ('monthly', 'MONTHLY')], default='daily', max_length=12),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
