version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./Backend/activityTracker/Dockerfile
      target: production
    container_name: 'api'
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - postgres-db
    networks:
      - my-network
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: ./FrontEnd/Dockerfile
      target: production
      args:
        VITE_API_BASE_URL: "/api/v1"
    container_name: 'frontend'
    restart: unless-stopped
    ports:
      - 5173:80
    depends_on:
      - api
    networks:
      - my-network

  postgres-db:
    image: postgres:18
    restart: unless-stopped
    container_name: 'postgres-db'
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - my-network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: postgres_data

networks:
  my-network:
    name: my-network
