# Generated by Django 5.2.10 on 2026-01-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
