# Generated by Django 5.2.10 on 2026-02-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0004_roadmapnotes_content_roadmapnotes_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmap',
            name='category',
        ),
    ]
