# Generated by Django 5.2.10 on 2026-01-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_account_valid_account_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='valid_account_type',
        ),
    ]
