# Generated by Django 5.2.10 on 2026-01-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('e-sewa', 'E-SEWA'), ('digital', 'Digital')], max_length=32),
        ),
    ]
