# Generated by Django 5.2.10 on 2026-01-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('digital', 'Digital')], max_length=32),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('loan-taken', 'LOAN-TAKEN'), ('loan-given', 'LOAN-GIVEN')], max_length=16),
        ),
    ]
