# Generated by Django 5.2.10 on 2026-02-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_category_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remaining_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
