# Generated by Django 5.2.10 on 2026-01-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('account_type__in', ['cash', 'bank', 'digital'])), name='valid_account_type'),
        ),
    ]
