# Generated by Django 5.2.10 on 2026-10-08 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_transaction_remaining_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_transactions', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('assets', 'ASSETS'), ('liabilities', 'LIABILIIES'), ('transfer', 'Transfer')], max_length=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('assets', 'ASSETS'), ('liabilities', 'LIABILIIES'), ('transfer', 'Transfer')], max_length=16),
        ),
    ]
