# Generated by Django 5.2.10 on 2026-08-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_delay', 'Task Delay'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('finance_alert', 'Finance Alert'), ('budget_exceeded', 'Budget Exceeded'), ('transaction_added', 'Transaction Added'), ('roadmap_milestone', 'Roadmap Milestone'), ('roadmap_delayed', 'Roadmap Delayed'), ('member_invited', 'Member Invited'), ('member_joined', 'Member Joined'), ('role_changed', 'Role Changed'), ('organization_updated', 'Organization Updated')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notification',
            name='source_type',
            field=models.CharField(choices=[('TASK', 'Task'), ('FINANCE', 'Finance'), ('ROADMAP', 'Roadmap'), ('MILESTONE', 'Milestone'), ('ORGANIZATION', 'Organization'), ('MEMBER', 'Member')], max_length=64),
        ),
    ]
