# Generated by Django 5.2.10 on 2026-02-08 16:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_roadmapnotes_milestone_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapnotes',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadmapnotes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadmapnotes',
            name='hours_spent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadmapnotes',
            name='roadmap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='roadmap.roadmap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadmapnotes',
            name='title',
            field=models.CharField(default='test', max_length=1024),
            preserve_default=False,
        ),
    ]
