# 1. Name of your pipeline
name: App CI/CD Pipeline

# 2. The Trigger Event: Run only when code is pushed to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  # JOB 1: Continuous Integration (Testing)
  run-tests:
    runs-on: ubuntu-latest # Tells GitHub to give us a fresh Ubuntu machine
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6 # An official action that clones your code onto the runner

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          # 'uses' is like calling a programming function, 'with' is how you pass arguments/parameters into that function.

      - name: Install App Dependencies
        run: pip install -r Backend/activityTracker/requirements.txt 
        # 'run' command directly runs command inside terminal, 
        # whereas 'uses' uses predefined set of command called actions
        # (foreg: logging into docker can take very long boilerplate commands)

      - name: Run Test Suite
        run: python Backend/activityTracker/manage.py test
        env:
          ENVIRONMENT: testing
          PYTHONPATH: Backend/activityTracker # If this fails, the whole pipeline stops right here!

  # JOB 2: Continuous Deployment (Build & Ship)
  build-and-ship:
    runs-on: ubuntu-latest
    needs: run-tests # Crucial: Don't run this job unless 'run-tests' passes successfully!
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6

      - name: Log in to GHCR
        uses: docker/login-action@v3 # Uses GitHub's official Docker login tool
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Automatically grabs your GitHub username
          password: ${{ secrets.GITHUB_TOKEN }} # An automated, temporary password given by GitHub

      - name: Create .env file
        run: |
          cat > .env << EOF
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          EOF

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Backend/activityTracker/Dockerfile
          target: production
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/tracker-backend:latest
            ghcr.io/${{ github.repository_owner }}/tracker-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./FrontEnd/Dockerfile
          target: production
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/tracker-frontend:latest
            ghcr.io/${{ github.repository_owner }}/tracker-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
